### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by liat128** [FaVorith/recursive-virustotal#3]
hi,
i have the "No module named 'virus_total_apis'" problem, although i did the commands that you mention to do. 
can you tell me what i need to do now? 
thanks

**Comment by FaVorith** [comment]
Hi Liat,

Thank you for trying out the script and your feedback. What is the output after you run
`pip install virustotal-api`
?

Thanks and regards,
Fabian

**Comment by FaVorith** [comment]
In lack of response, I assume the problem has been solved.
